server:
    port: 8080

spring:
    datasource:
    #postgresql://[hostname] [db] [user] [password]
        url: jdbc:postgres://postgres1:rJTIVn03odteiQ3GdvDoptE1UbjgvwXr@dpg-cperjnf109ks73fj9nmg-a.oregon-postgres.render.com/fatecjava_4c88
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
