server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cperjnf109ks73fj9nmg-a.oregon-postgres.render.com:5432/fatecjava_4c88
        driver-class-name: org.postgresql.Driver
        username: postgres1
        password: rJTIVn03odteiQ3GdvDoptE1UbjgvwXr
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
